### PR TITLE
adding link of a working example located in the sample-projects repo

### PR DESCRIPTION
**Pull request by lolski**
- adding link of a working example located within the sample-projects repository

### CODE REVIEW

**Comment by fppt** [comment]
Maybe this PR can actually go into the stable branch @lolski  ?

**Comment by lolski** [comment]
@fppt ok!

**Comment by fppt** [comment]
Errrrr . . .  now you merging master into stable (look at the commits) probably don't want to do that just because of a single line change :)

**Comment by lolski** [comment]
Apparently changing the base from `master` to `stable` did not bring the intended effect. Closing this PR and submitting a proper one

**Pull request closed without merging**
