### PR TITLE
Fix semantics when inferring types

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
please retest this please - Command execution failed

**Comment by kasper-piskorski** [comment]
please retest this please - ai.grakn.test.engine.controller.CommitLogControllerTest.whenCommittingGraph_TaskManagerReceivesCountTask

**Comment by fppt** [comment]
@kasper-piskorski please make a merge PR into central with these changes.

**Comment by kasper-piskorski** [comment]
Merged to master here: https://github.com/graknlabs/grakn/pull/1690

**Pull request merged**
