### PR TITLE
Support an optional semicolon after every graql shell command

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
please retest this please

**Comment by fppt** [comment]
please retest this please

**Comment by aelred** [comment]
...please retest this please

**Comment by haikalpribadi** [comment]
Can one of the admins verify this patch?

**Comment by sheldonkhall** [comment]
please retest this please

**Comment by fppt** [comment]
@aelred this one has been sitting here for a while. Could you rebase so we can get this one in ?

**Comment by aelred** [comment]
please retest this please

**Comment by aelred** [comment]
please retest this please

**Comment by aelred** [comment]
what do you want jenkins I'll give you anything just please retest this please

**Comment by aelred** [comment]
jenkins listen when I said anything I meant ANYTHING so please please retest this please

**Comment by fppt** [comment]
Virtual hug @aelred I feel your pain !

**Comment by alexandraorth** [comment]
please retest this please

**Comment by aelred** [comment]
please retest this please please please

**Pull request merged**
