### PR TITLE
Shallow copy when copying explanations

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
please retest this please

**Comment by kasper-piskorski** [comment]
please retest this please - Command execution failed

**Comment by burukuru** [comment]
!rtg - fixing the commit status.

**Comment by kasper-piskorski** [comment]
please retest this please -     ai.grakn.test.engine.controller.CommitLogControllerTest.whenCommittingGraph_TaskManagerReceivesCountTask
 ai.grakn.factory.TitanPreviousPropertyStepTest.whenFilteringAPropertyToBeEqualToAPreviousProperty_UseTitanGraphStep
    ai.grakn.factory.TitanPreviousPropertyStepTest.whenUsingATitanGraph_ApplyStrategy

**Pull request merged**
