### PR TITLE
[Stable] Answer consumption fix

### PR DESCRIPTION
**Pull request by kasper-piskorski**
Fixes problems with consuming (acknowledging) answers to rules with single-atom bodies:
* they might be not unified correctly
* they could contain incorrect explanations

**NB: This fix is already present in master, just porting it to stable.**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
This requires merging either: 
https://github.com/graknlabs/grakn/pull/2572 or
https://github.com/graknlabs/grakn/pull/2571
to pass tests.

**Comment by lolski** [comment]
@kasper-piskorski Same as with https://github.com/graknlabs/grakn/pull/2571, as an unfamiliar reader, more descriptions about the PR as has been outlined by @aelred 's w.r.t the new review process would be helpful.

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
@fppt @lolski please review this as well ;p

**Pull request merged**
