### PR TITLE
FIx several REST API bugs

### PR DESCRIPTION
**Pull request by aelred**
btw I put this against `master` because I thought the changes were kind of serious, even though they are probably technically bug fixes. Let me know if you think it should be `stable`!

### CODE REVIEW

**Comment by aelred** [comment]
This PR has probably broke dashboard, so best not merge till we check

**Comment by marco-scoppetta** [comment]
@aelred why do you do this to me Felix?

**Comment by aelred** [comment]
@marco-scoppetta merry christmas!

**Comment by aelred** [comment]
@marco-scoppetta this is ready to review. We can work out if there's another way to do the #page.html redirect thing!

**Comment by fppt** [comment]
I would say move this to be against stable @aelred

**Pull request merged**
