### PR TITLE
Add deprecated support for keywords `lhs` and `rhs`

### PR DESCRIPTION
**Pull request by aelred**
These have been replaced by `when` and `then`.

Keeping these keywords for just one more version means that we can test both `master` and `stable` using the same Graql queries.

### CODE REVIEW

**Comment by aelred** [comment]
@fppt Done!

**Comment by fppt** [comment]
rtg

**Comment by aelred** [comment]
!rtg - all failing tests ignored and logged to TP

**Comment by fppt** [comment]
!rtg - ran ignored test fro some odd reason

**Pull request merged**
