### PR TITLE
Low and high priority queues

### PR DESCRIPTION
**Pull request by alexandraorth**

### CODE REVIEW

**Comment by burukuru** [comment]
to the back of the queue and retest this please

**Comment by alexandraorth** [comment]
please retest this please - `npm ERR! `

**Comment by bolerio** [comment]
Oh wow, tests passed, is this ready to go in?

**Comment by alexandraorth** [comment]
Yes, @bolerio , this can go in. Its using the tactic of a single task runner for each queue. So by default we have 16 low priority and 16 high priority task runners.

**Pull request merged**
