### PR TITLE
New docs figures

### PR DESCRIPTION
**Pull request by mikonapoli**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
@mikonapoli hmm did you checkout from central master?

**Comment by mikonapoli** [comment]
I am afraid I haven't at this point :(

**Comment by mikonapoli** [comment]
I meant I have. Crap

**Comment by kasper-piskorski** [comment]
I mean it looks like you are trying to push commits from master to stable

**Comment by mikonapoli** [comment]
you are right

2017-09-05 19:19 GMT+01:00 Kasper Piskorski <notifications@github.com>:

**Pull request closed without merging**
