### PR TITLE
Adding bash tests with shunit2

### PR DESCRIPTION
**Pull request by burukuru**
Starts stack using grakn.sh
Imports data
Runs 2 simple checks
Only runs in titan profile

Using shunit2 instead of BATS because shunit2 allows for single setup
and teardown for both tests.

### CODE REVIEW

**Comment by burukuru** [comment]
retest this please

**Comment by burukuru** [comment]
This actually needs to be in integration-test phase as it needs the packaged dist. I'll test jenkins once PMD has gone in and redo this one.

**Comment by burukuru** [comment]
retest this please

**Comment by fppt** [comment]
@burukuru this needs a rebase please

**Comment by aelred** [comment]
@burukuru this one should be fixed once I merge this: https://github.com/graknlabs/grakn/pull/996

**Comment by bolerio** [comment]
retest this please

**Comment by aelred** [comment]
@burukuru now we've merged #996 you can rebase/merge with central

**Comment by burukuru** [comment]
@aelred my PR still hanging :(

**Comment by aelred** [comment]
@burukuru I think we found a similar issue on Miko's branch. #1011 has this fix now. I'm sure someday this PR will go in if we believe!

**Comment by fppt** [comment]
@burukuru the PR Felix mentioned has been merged when you have time could you rebase this PR and see if we can get it passing.

**Comment by fppt** [comment]
@burukuru what's going on with this PR? Been here for a while?

**Comment by burukuru** [comment]
I think a PR changed the hierarchy of modules, I'll fix this now.

**Comment by fppt** [comment]
Ah yes there were two PRs which changed the hierarchy.

**Pull request merged**
