### PR TITLE
Merging from stable dashboard fix on resource owners.

### PR DESCRIPTION
**Pull request by marco-scoppetta**

### CODE REVIEW

**Comment by marco-scoppetta** [comment]
!rtg - ai.grakn.factory.TitanPreviousPropertyStepTest.whenFilteringAPropertyToBeEqualToAPreviousProperty_UseTitanGraphStep

**Comment by burukuru** [comment]
!rtg

**Comment by fppt** [comment]
!rtg

**Comment by fppt** [comment]
Closing as this was already addressed in: https://github.com/graknlabs/grakn/pull/1703

**Pull request closed without merging**
