### PR TITLE
Refactor to Grakn

### PR DESCRIPTION
**Pull request by fppt**

### CODE REVIEW

**Comment by haikalpribadi** [comment]
Can one of the admins verify this patch?

**Comment by fppt** [comment]
I am an admin !!! Mwhahahahahah . . . We need to shut off robo Haikal before I develop an unhealthy habit of talking with him :)

**Comment by haikalpribadi** [comment]
Can one of the admins verify this patch?

**Comment by fppt** [comment]
please retest this please

**Pull request merged**
