### PR TITLE
Run tests in random order

### PR DESCRIPTION
**Pull request by fppt**
This is so I can help find the flakier flaky tests and get rid of them.

### CODE REVIEW

**Comment by aelred** [comment]
Great idea! Is the idea to make this the default?

**Comment by fppt** [comment]
Yep. I can't get PIT mutation testing going until I get rid of our flaky tests. So that's my next goal

**Comment by fppt** [comment]
@aelred should we talk about merging this? I kind of have reservations but in the long run it may be a good thing :/

**Comment by aelred** [comment]
@fppt I'm OK with merging it. Like you say, we'll find lots of issues very fast.

**Comment by fppt** [comment]
Alright merging it. But if we find that PRs never pass we can pull it out.

**Pull request merged**
