### PR TITLE
Add neq predicate state to accomodate recursive queries with neq predicates

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by fppt** [comment]
!rtg - I suspect the refactors have broken this.

**Comment by kasper-piskorski** [comment]
!rtg - GraknTxJanusTest

**Comment by kasper-piskorski** [comment]
!rtg - GraknTxJanusTest

**Comment by kasper-piskorski** [comment]
!rtg - GraknTxJanusTest

**Comment by kasper-piskorski** [comment]
!rtg - ai.grakn.graql.internal.query.InsertQueryTest.ai.grakn.graql.internal.query.InsertQueryTest - timeout

**Pull request merged**
