### PR TITLE
Adding a more informative failure diagnostic output if the script somehow fails to start

### PR DESCRIPTION
**Pull request by lolski**

### CODE REVIEW

**Comment by fppt** [comment]
Maybe should be on stable considering it looks like we have to hotfix 0.17 release?

**Comment by lolski** [comment]
@fppt Hmm should we? this is intended to print informative logs in order to help identifying CI failures.

**Comment by fppt** [comment]
Ah I did not realise it was not meant for external use. In that case leave as is.

**Comment by fppt** [comment]
Maybe we can make a verbose flag in this case? That's way we don't have to remember to take this our later.

**Comment by lolski** [comment]
@fppt Actually, this should prove to be useful for users in case they're having problems with the start up / shut down.

I am just of the opinion that we should not include it on the very next hotfix - as we might want to tweak the stuff which is printed, still

what do you think?

**Comment by fppt** [comment]
I agree lets not release it with the hotfix but we should add a flag so that when we debug people issues we can have more info to play with.

**Comment by lolski** [comment]
@fppt `grakn server status --verbose`?

**Comment by lolski** [comment]
!rtg - ai.grakn.factory.JanusPreviousPropertyStepTest  Time elapsed: 17.485 sec  <<< ERROR!
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))

**Comment by lolski** [comment]
!ci - ai.grakn.factory.JanusPreviousPropertyStepTest  Time elapsed: 17.485 sec  <<< ERROR!
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))

**Comment by lolski** [comment]
!rtg - All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))

**Pull request merged**
