### PR TITLE
[Stable] Fix problem with atom equivalence when comparing relation with repeating roles

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
please retest this please - ai.grakn.engine.controller.AuthControllerTest.ai.grakn.engine.controller.AuthControllerTest
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseContainsValidHALObjects
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseContentTypeIsHAL
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseIsNotEmpty
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseStatusIs200
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithTextType_ResponseIsCorrect
ai.grakn.engine.session.EngineGraknSessionTest.testBatchLoadingGraphsInitialisedCorrectly
ai.grakn.engine.session.EngineGraknSessionTest.testDifferentFactoriesReturnTheSameGraph
ai.grakn.graql.internal.query.DeleteQueryTest.testDeleteEntityTypeWithNoInstances
ai.grakn.graql.internal.query.InsertQueryTest.testInsertRuleSub

**Comment by kasper-piskorski** [comment]
please retest this please - ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseContainsValidHALObjects
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseContentTypeIsHAL
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseIsNotEmpty
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithHALType_ResponseStatusIs200
ai.grakn.engine.controller.GraqlControllerGETTest.ZGETGraqlComputePathWithTextType_ResponseIsCorrect

**Comment by kasper-piskorski** [comment]
please retest this please - ai.grakn.graql.internal.query.DeleteQueryTest.testDeleteEntityTypeWithNoInstances
ai.grakn.graql.internal.query.InsertQueryTest.testInsertRuleSub
ai.grakn.graql.internal.query.InsertQueryTest.testInsertSub
ai.grakn.graql.internal.query.InsertQueryTest.testInsertRuleType

**Comment by fppt** [comment]
!rtg

**Comment by fppt** [comment]
@kasper-piskorski please merge this into master

**Comment by kasper-piskorski** [comment]
merged here: https://github.com/graknlabs/grakn/pull/1866

**Pull request merged**
