### PR TITLE
Make travis build and test modules in parallel

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
!rtg - redis failures

**Comment by fppt** [comment]
I am going to be an ass and ask that this passes . . . . 6 times. So 1 pass!

**Comment by fppt** [comment]
2 !

**Comment by fppt** [comment]
3 !

**Comment by fppt** [comment]
4 !

**Comment by fppt** [comment]
5!

**Comment by fppt** [comment]
and 6

**Pull request merged**
