### PR TITLE
Upgrading jline from 2.12 to 2.14.6 (native-image)

### PR DESCRIPTION
**Pull request by neomatrix369**
## What is the goal of this PR?

Upgrade jline from 2.12 to 2.14.6  to enable building an OS-specific native-image

## What are the changes implemented in this PR?

Change to the bazel dependencies config file, it's a version upgrade.

PS: did check with @vmax, if this change had any negative impact.

### CODE REVIEW

**Comment by neomatrix369** [comment]
> Thank you, @neomatrix369 ! Once you make a change in `dependencies.yaml`, please run `./dependencies/maven/update.sh` and this will generate new `depedencies.bzl` for bazel which should be commited into this PR. Before submitting the PR, please also test the build by running `bazel build //...`. Thank you again!

I was trying the easy way out, wasn't I? I'm running these steps as I write, will update PR asap.

**Comment by lolski** [comment]
@neomatrix369 please do and let us know if the build step succeeded.

Just a heads up the, `build` step in our Continuous Integration will still fail due to another, completely unrelated issue: https://github.com/graknlabs/grakn/issues/5347.

**Comment by neomatrix369** [comment]
> @neomatrix369 please do and let us know if you can run `bazel build //...` step successfully.
> 
> Just a heads up the, `build` step in our Continuous Integration will still fail due to another, completely unrelated issue: #5347.

It's in progress atm, will let you guys know asap

**Comment by neomatrix369** [comment]
```java
 ./dependencies/maven/update.sh
Starting local Bazel server and connecting to it...
DEBUG: Rule 'graknlabs_build_tools' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564486142 +0300"
DEBUG: Rule 'graknlabs_graql' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564504617 +0000"
DEBUG: Rule 'graknlabs_bazel_distribution' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564413727 +0300"
INFO: Analyzed target @graknlabs_build_tools//bazel:bazel-deps (19 packages loaded, 476 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/grakn/.cache/bazel/_bazel_grakn/ca1f4c80d5117439b1e43552b4dab700/sandbox
INFO: Elapsed time: 75.583s, Critical Path: 2.05s
INFO: 0 processes.
INFO: Running command line: bazel-bin/external/graknlabs_build_tools/bazel/bazel-deps generate -r /home/grakn/shared/grakn/dependencies/maven/../../ -s dependencies/maven/dependencies.bzl -d dependencies/maven/dependencies.yaml
wrote 261 targets in 148 BUILD files
```

```java
grakn@39c864ab4dc0:~/shared/grakn$ bazel build //:assemble-linux-targz
DEBUG: Rule 'graknlabs_build_tools' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564486142 +0300"
DEBUG: Rule 'graknlabs_graql' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564504617 +0000"
DEBUG: Rule 'graknlabs_bazel_distribution' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564413727 +0300"
DEBUG: Rule 'graknlabs_protocol' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564504529 +0000"
INFO: Analyzed target //:assemble-linux-targz (481 packages loaded, 2722 targets configured).
INFO: Found 1 target...
```

**Comment by lolski** [comment]
Closing this PR since we've already moved to JLine 3.17.1: https://github.com/graknlabs/dependencies/blob/master/library/maven/artifacts.bzl

Thanks @neomatrix369 !

**Pull request closed without merging**
