### PR TITLE
Using mock redis and restructuring test Rules

### PR DESCRIPTION
**Pull request by pluraliseseverythings**

### CODE REVIEW

**Comment by pluraliseseverythings** [comment]
!rtg - jenkins didn't build

**Comment by pluraliseseverythings** [comment]
!rtg

**Comment by fppt** [comment]
@pluraliseseverythings I sense a lot has changed since creating this PR. Maybe we can close it?

**Comment by fppt** [comment]
@pluraliseseverythings I am closing this since it is quiet old and I think I am working on it now anyway :)

**Pull request closed without merging**
