### PR TITLE
Remove testing profiles from grakn-test

### PR DESCRIPTION
**Pull request by mikonapoli**
- Put the testing profiles in a separate POM module
- Have grakn-test inherit from the newly created grakn-test-profiles
- Minor Pom Fixes to avoid a bunch of warnings

If a module needs the test profiles, it should inherit from grakn-test-profile instead of grakn.

This is the next step into moving the tests back into their own modules.

### CODE REVIEW

**Comment by mikonapoli** [comment]
Any idea why this is failing? Is it an actual failure or a random Jenkins quirk?

Also: it seems to have actually nothing to do with what this PR is about...

**Comment by fppt** [comment]
please retest this please

**Comment by fppt** [comment]
@mikonapoli That one test failure I have seen before (so it's a random passing/failing test). Has to do with engine still being unstable at the moment I think.

**Comment by mikonapoli** [comment]
@fppt Ok, thanks. I wish there was a way to run that test before, so that it does not fail after more than one hour...

**Comment by fppt** [comment]
@mikonapoli Well one of the nice bright sides of the test division you are working on is that we will likely not have to wait one hour. We will fail faster, which is always nice :)

**Comment by mikonapoli** [comment]
If this goes in, I can start moving tests away from grakn-test but I need to be sure that everybody is fine with the change.

I have added a module that contains the testing profiles called `grakn-test-profiles`. Any module that needs profile-based tests (at the moment only `grakn-test`, but there will be more as soon as the tests start moving out of it) will need to be the child of this one instead of the main pom.

**Comment by mikonapoli** [comment]
GITHUB IS LYING! My PR passed, it's Docker's fault :(

**Pull request merged**
