### PR TITLE
Moved from NPM to Yarn for js packages management

### PR DESCRIPTION
**Pull request by marco-scoppetta**
- also updated Babel to use env instead of es2015

### CODE REVIEW

**Comment by burukuru** [comment]
!rtg - GO YARN!

**Comment by burukuru** [comment]
!rtg - someone stole my VM

**Comment by burukuru** [comment]
!rtg - new day means new beginnings

**Comment by marco-scoppetta** [comment]
!rtg - Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project test-integration: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

**Comment by burukuru** [comment]
Will this be an even better PR than Janus merge??

**Pull request merged**
