### PR TITLE
[Stable] To Miko with love (aka various small performance fixes)

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
@mikonapoli  please review, it should fix the onshore problem :)

**Comment by kasper-piskorski** [comment]
Yes it is arbitrary, in fact there's a number of arbitrary parameters. Until we use some graph statistics I think we have to stick to using them.

**Comment by kasper-piskorski** [comment]
Regarding tests, we don't have any explicit tests testing resolution order. They are all tested on a query basis.

**Comment by fppt** [comment]
@kasper-piskorski merge this into master please

**Pull request merged**
