### PR TITLE
Test snb readme update: how to interpret the verification result

### PR DESCRIPTION
**Pull request by lolski**
README updated to include how to interpret the verification result. The PR targets `stable`.

### CODE REVIEW

**Comment by lolski** [comment]
!rtg

https://jenkins.grakn.ai/blue/organizations/jenkins/grakn/detail/PR-2567/2/tests

```
java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:4567/kb
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:4567/kb
```

**Comment by aelred** [comment]
@lolski have you merged with latest `stable`? That failure _should_ be fixed.

**Comment by lolski** [comment]
@aelred aah you're right. i remember i saw that message on slack. will be merging now

**Comment by lolski** [comment]
@aelred I did not merge with latest `stable` according to your suggestion, however, it seems that the tests have passed. Would you still advise to do the merge with `stable`, or are we good with merging the PR?

**Comment by aelred** [comment]
@lolski nah, it's all good. Jenkins always merges with `stable` prior to testing. The only reason to do it manually is to force a re-test.

**Pull request merged**
