### PR TITLE
Fix issue with slow queries when comparing values of resources

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
hmm.. travis doesn't run against `stable`?

**Comment by aelred** [comment]
!rtg - `CommitLogControllerTest.whenCommittingGraph_TaskManagerReceivesCountTask`

**Comment by fppt** [comment]
It used to. Look at this PR for example: https://github.com/graknlabs/grakn/pull/1705

**Comment by aelred** [comment]
I'll rebase to see if I can invoke it to run.

**Comment by fppt** [comment]
Please create a merge into master and reference it here.

**Comment by aelred** [comment]
Merging into master in #1708

**Pull request merged**
