### PR TITLE
 [Stable] Look at neighbours of untyped role players to prioritise relation types

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
!rtg - cassandra failure (during ai.grakn.graql.internal.query.aggregate.AggregateTest.ai.grakn.graql.internal.query.aggregate.AggregateTest)

**Comment by kasper-piskorski** [comment]
!rtg - ai.grakn.client.BatchMutatorClientTest.whenEngineRESTFailsWhileLoadingWithRetryTrue_LoaderRetriesAndWaits

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by fppt** [comment]
@kasper-piskorski and you resolve the conflicts please?

**Pull request merged**
