### PR TITLE
Add `plays` syntax to retrieve instances that play a particular role type

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
Please don't merge until reasoner supports this property!

**Comment by aelred** [comment]
please retest this please

**Comment by aelred** [comment]
@fppt I'm not sure if Jenkins has already run for this or not. Think I should merge?

**Comment by fppt** [comment]
@aelred wait for jenkins to run again. Just to make sure other changes have not broken this PR.

**Comment by aelred** [comment]
@fppt the thing is, I'm not convinced Jenkins _will_ run again. When I came in today, it was still yellow stating "default — Build triggered. sha1 is merged.".

**Comment by fppt** [comment]
@aelred Ah. Maybe close and reopen the branch? Oh resubmit the PR under a different name?

**Comment by aelred** [comment]
jenkins please listen to me ;_;

**Pull request closed without merging**
