### PR TITLE
Bug #16192: Fix failing property test. 

### PR DESCRIPTION
**Pull request by fppt**
I would like to test this 10 times before going in. I will just test on travis because this seems to fail on travis as well

### CODE REVIEW

**Comment by aelred** [comment]
one pass

**Comment by fppt** [comment]
two passes

**Comment by fppt** [comment]
three passes

**Comment by fppt** [comment]
four passes

**Comment by fppt** [comment]
five passes

**Comment by fppt** [comment]
six passes

**Comment by fppt** [comment]
seven passes

**Comment by fppt** [comment]
eight passes . . . almost there

**Comment by fppt** [comment]
nine passes

**Pull request merged**
