### PR TITLE
Fixed shell batch loading. Restored tests

### PR DESCRIPTION
**Pull request by pluraliseseverythings**

### CODE REVIEW

**Comment by pluraliseseverythings** [comment]
!rtg

**Comment by pluraliseseverythings** [comment]
y u no !rtg

**Comment by aelred** [comment]
dw dom i will !rtg

**Comment by aelred** [comment]
!rtg

**Comment by pluraliseseverythings** [comment]
!rtg

**Comment by pluraliseseverythings** [comment]
!rtg

**Pull request merged**
