### PR TITLE
Introduce type variable rewriting

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by burukuru** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by kasper-piskorski** [comment]
review anyone?

**Comment by kasper-piskorski** [comment]
Anyone pretty please :)?

**Pull request merged**
