### PR TITLE
Make grakn-test-profiles parent of grakn-dist

### PR DESCRIPTION
**Pull request by burukuru**
The bash tests only run in the titan profile so need this dependency.

### CODE REVIEW

**Comment by burukuru** [comment]
retest this please

**Comment by burukuru** [comment]
I'm not sure why the PR is failing on these two tests:
```
ai.grakn.test.engine.GraknEngineFailoverIT.whenSubmittingTasksToTwoEngines_TheyComplete
ai.grakn.test.engine.GraknEngineFailoverIT.whenSubmittingTasksToOneEngine_TheyComplete
```
Does anyone have any input on how I can make the profile options available in grakn-dist tests?
I want the titan profile to set grakn.skip-bash-tests to false.

**Comment by fppt** [comment]
@alexandraorth @aelred I think those tests fall under your area of expertise?

I remember those used to fail randomly. Is that still the case?

**Comment by aelred** [comment]
I'll look into it. I have no idea why this change should cause that failure...

**Comment by alexandraorth** [comment]
The test that failed (`GraknEngineFailoverIT`) was one that unzips and runs the packaged distribution. This error was actually because the package was broken. I'm going to create a specific test that only runs the package so that we don't keep finding these issues in the failover tests and getting confused.

**Comment by burukuru** [comment]
Thanks for spotting that Alex. Changing the parent changes project.basedir which we redefine; that's used in the assembly file so config includes fail.

**Comment by burukuru** [comment]
Don't merge this just yet, the tests I added don't seem to be triggered still.

**Pull request closed without merging**
