### PR TITLE
Dashboard: Fixed linking resources to owner nodes in graph.

### PR DESCRIPTION
**Pull request by marco-scoppetta**

### CODE REVIEW

**Comment by marco-scoppetta** [comment]
!rtg

**Comment by marco-scoppetta** [comment]
!rtg

**Comment by fppt** [comment]
@marco-scoppetta once again please merge this fix into master and reference it here.

**Comment by marco-scoppetta** [comment]
Bug fix merged into master with [#1699](https://github.com/graknlabs/grakn/pull/1699)

**Comment by kasper-piskorski** [comment]
Merged here: https://github.com/graknlabs/grakn/pull/1703

**Pull request merged**
