### PR TITLE
Make sure redis is killed after continuous integration

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by burukuru** [comment]
!rtg

**Comment by aelred** [comment]
!rtg - Failed to execute goal on project test-integration: Could not resolve dependencies for project ai.grakn:test-integration:jar:PR-2309: Failed to collect dependencies at net.lingala.zip4j:zip4j:jar:1.3.2: Failed to read artifact descriptor for net.lingala.zip4j:zip4j:jar:1.3.2: Could not transfer artifact net.lingala.zip4j:zip4j:pom:1.3.2 from/to releases (https://maven.grakn.ai/content/repositories/releases/): maven.grakn.ai: No address associated with hostname

**Comment by aelred** [comment]
@fppt can you review this? I will merge it so long as `pr-merge` passes.

**Comment by aelred** [comment]
!rtg - timeout

**Pull request merged**
