### PR TITLE
Fix bug where Graql shell would log to the engine log file

### PR DESCRIPTION
**Pull request by aelred**
# Why is this PR needed?

Fixes a high-priority bug that comes up when Graql shell does not have permission to access the same log file as engine.

# What does the PR do?

Simply stops Graql shell logging! It only logged in one specific instance, so this is not a huge issue.

I've also removed some unused code: there was a `Client#main` method that is completely unreferenced in the code-base.

# Does it break backwards compatibility?

No.

# List of future improvements not on this PR

Maybe introducing a client-side logging configuration? That way we can still log in the Graql shell without an issue. However, bear in mind right now we very rarely log on the client-side.

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
Can we push it to stable? Then we would deploy the next release.

**Comment by aelred** [comment]
@kasper-piskorski good point, I forgot about `stable`!

**Comment by lolski** [comment]
@aelred w.r.t future improvement: I think it is safe to assume that we always want to print errors directly to `stdout` / `stderr` in case of `graql console`. based on the use case, user would normally expect errors to be displayed straight away rather than logged in a log file

**Comment by aelred** [comment]
@lolski I think I agree! So yay less future work

**Comment by lolski** [comment]
Looking at the exception Kasper posted it seems to come from here:
```
	at 	at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:35)
	at 	at ai.grakn.graql.GraqlClient.connect(GraqlClient.java:42)
	at 	at ai.grakn.graql.JsonSession.<init>(JsonSession.java:78)
	at 	at ai.grakn.graql.JsonSession.<init>(JsonSession.java:71)
	at 	at ai.grakn.graql.GraqlShell.<init>(GraqlShell.java:336)
	at 	at ai.grakn.graql.GraqlShell.runShell(GraqlShell.java:260)
	at 	at ai.grakn.graql.GraqlShell.runShell(GraqlShell.java:170)
	at 	at ai.grakn.graql.GraqlShell.main(GraqlShell.java:165)
	at 	at ai.grakn.dist.DistGraql.run(DistGraql.java:52)
	at 	at ai.grakn.dist.DistGraql.main(DistGraql.java:44)
```

Maybe we missed a couple of other loggers?

**Comment by aelred** [comment]
@lolski one of our dependencies is using a logger - so it's harder to remove. I think we may need to come up with a client-specific logging config somehow - one that either is no-op, or prints to stdout/stderr.

**Comment by aelred** [comment]
@kasper-piskorski let me know if the new change has fixed it. It should disable logging completely client-side.

**Comment by kasper-piskorski** [comment]
same problem still:
```
11:18:11,077 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[MAIN] - openFile(/opt/grakn/grakn-dist-1.1.0-SNAPSHOT/./logs//grakn.log,true) call failed. java.io.FileNotFoundException: /opt/grakn/grakn-dist-1.1.0-SNAPSHOT/./logs/grakn.log (Permission denied)
	at java.io.FileNotFoundException: /opt/grakn/grakn-dist-1.1.0-SNAPSHOT/./logs/grakn.log (Permission denied)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:149)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:390)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:340)
	at 	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:38)
	at 	at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:32)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at 	at java.lang.Class.newInstance(Class.java:442)
	at 	at org.eclipse.jetty.util.log.Log.initialized(Log.java:175)
	at 	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:298)
	at 	at org.eclipse.jetty.util.log.Log.getLogger(Log.java:288)
	at 	at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:35)
	at 	at ai.grakn.graql.GraqlClient.connect(GraqlClient.java:42)
	at 	at ai.grakn.graql.JsonSession.<init>(JsonSession.java:78)
	at 	at ai.grakn.graql.JsonSession.<init>(JsonSession.java:71)
	at 	at ai.grakn.graql.GraqlShell.<init>(GraqlShell.java:336)
	at 	at ai.grakn.graql.GraqlShell.runShell(GraqlShell.java:260)
	at 	at ai.grakn.graql.GraqlShell.runShell(GraqlShell.java:170)
	at 	at ai.grakn.graql.GraqlShell.main(GraqlShell.java:165)
	at 	at ai.grakn.dist.DistGraql.run(DistGraql.java:52)
	at 	at ai.grakn.dist.DistGraql.main(DistGraql.java:44)
```

**Comment by aelred** [comment]
@kasper-piskorski I promise this is the last time 👍

Can you test it once more manually?

I checked it worked on my machine with:
```
$ sudo grakn server start
$ graql console
```
So the logs were owned by root, and it started (previously it would crash like yours).

**Comment by kasper-piskorski** [comment]
@aelred ok now it works!

**Comment by aelred** [comment]
Yesss! Now the tests are failing though :D

**Pull request merged**
