### PR TITLE
[do not squash] Homebrew slow startup from fat directory workaround merge to master

### PR DESCRIPTION
**Pull request by lolski**
Merge homebrew changes from stable to master

### CODE REVIEW

**Comment by lolski** [comment]
!rtg - Error in stopping Grakn: Expected to find 0 running Redis process. Found  1

**Comment by lolski** [comment]
!ci - 
```
whenSending100InsertQueries_100EntitiesAreLoadedIntoGraph(ai.grakn.test.client.BatchExecutorClientTest)  Time elapsed: 2.706 sec  <<< FAILURE!
java.lang.AssertionError: expected:<100> but was:<81>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at ai.grakn.test.client.BatchExecutorClientTest.whenSending100InsertQueries_100EntitiesAreLoadedIntoGraph(BatchExecutorClientTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```

**Comment by lolski** [comment]
retriggering test with fake commit due to
```
 > git init /home/ubuntu/workspace/grakn_PR-2342-MKPYB2XU3ULNLR7ONR3WGFA5U6PRT4VTTJ2NRYB34KOBO3BBZT6A # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/ubuntu/workspace/grakn_PR-2342-MKPYB2XU3ULNLR7ONR3WGFA5U6PRT4VTTJ2NRYB34KOBO3BBZT6A
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:717)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:511)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:205)
	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
	at hudson.remoting.Request$2.run(Request.java:356)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to aws-jenkins-agent (sir-mbfi4sym)
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1655)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:308)
		at hudson.remoting.Channel.call(Channel.java:904)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy76.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1075)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:260)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		... 4 more
Caused by: hudson.plugins.git.GitException: Command "git init /home/ubuntu/workspace/grakn_PR-2342-MKPYB2XU3ULNLR7ONR3WGFA5U6PRT4VTTJ2NRYB34KOBO3BBZT6A" returned status code 128:
stdout: 
stderr: fatal: cannot stat template '/usr/share/git-core/templates/hooks/pre-applypatch.sample.dpkg-new': No such file or directory


```

**Comment by fppt** [comment]
@lolski there are a bit too many junk commits for me to merge. . . what @aelred said

**Comment by fppt** [comment]
Just get rid of the junk commits.

**Comment by lolski** [comment]
@aelred Yesss!!!!!! Yeah i'll squash them right now

**Pull request merged**
