### PR TITLE
Some Test Suite Adjustments

### PR DESCRIPTION
**Pull request by bolerio**
1) Some more classes refactored into main grakn-test artifact.

2) Added a new flag and a new grakn.properties (conf/test/cluster) in order to be able to execute all unit and integration tests against an arbitrary cluster/endpoint rather than the embedded server components.

### CODE REVIEW

**Comment by burukuru** [comment]
!rtg

**Comment by bolerio** [comment]
!rtg

**Comment by bolerio** [comment]
!rtg

**Comment by bolerio** [comment]
@fppt yes: https://work.grakn.ai/entity/15396

**Comment by bolerio** [comment]
oops, I clicked on "Close and comment" instead of just "Comment" so it restarted testing :(

**Comment by fppt** [comment]
no worries. No changes so we ca merge

**Pull request merged**
