### PR TITLE
Dynamically merge resources which can be created in highly concurrent…

### PR DESCRIPTION
**Pull request by fppt**
… environments.

This should not be merged until we check if it has helped the Markit load. This is another high impact change from me :).

### CODE REVIEW

**Comment by fppt** [comment]
@mikonapoli when you have time could you try the markit load using this PR?

**Comment by mikonapoli** [comment]
@fppt should I wait for the tests to pass first?

**Comment by fppt** [comment]
@aelred I think it's "safe" to put this in.

**Comment by aelred** [comment]
@fppt you're right. I avoided this one because it had a scary complicated name :P

**Pull request merged**
