### PR TITLE
Fix performance when traversing to concept subs

### PR DESCRIPTION
**Pull request by aelred**
we actually don't know if this works just yet

### CODE REVIEW

**Comment by fppt** [comment]
@aelred it looks good to me but let's confirm the fix first.

**Comment by aelred** [comment]
@fppt good call! It doesn't work :P

**Comment by aelred** [comment]
@fppt please re-review

@mikonapoli if you have time, can you confirm the Markit query is now fast? I ran it locally and it seems to be, but this has taken so long that we should make sure we get it right.

**Comment by fppt** [comment]
Still looks good to me. Not merging just because of the title of the PR. @aelred merge at will.

**Pull request merged**
