### PR TITLE
removed jwt handler

### PR DESCRIPTION
**Pull request by micheleorsi**

### CODE REVIEW

**Comment by micheleorsi** [comment]
!rtg cannot reproduce

**Comment by micheleorsi** [comment]
Thanks @aelred !
I already searched for "password" and "jwt" and I already removed everything.
I will have a look at `GraqlShell` and dashboard endpoint with @marco-scoppetta

**Comment by fppt** [comment]
With regards to more code killing inside `SystemKeyspace#loadSystemSchema` you can kill all the user related stuff.

**Comment by micheleorsi** [comment]
!rtg cannot reproduce

**Comment by micheleorsi** [comment]
!rtg cannot reproduce

**Comment by aelred** [comment]
Yay! Nearly 1500 lines gone 😄

**Pull request merged**
