### PR TITLE
Fix problem with query ambiguity when building hal explanation

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by kasper-piskorski** [comment]
!rtg

**Comment by marco-scoppetta** [comment]
!rtg

**Comment by marco-scoppetta** [comment]
!ci

**Comment by marco-scoppetta** [comment]
!ci

**Comment by kasper-piskorski** [comment]
!ci

**Comment by kasper-piskorski** [comment]
@aelred merge time :)?

**Pull request merged**
