### PR TITLE
Add triggers phrases for githubPullRequest.

### PR DESCRIPTION
**Pull request by burukuru**

### CODE REVIEW

**Comment by burukuru** [comment]
!rtg

**Comment by burukuru** [comment]
This fixes the !rtg command.

I added this plugin which gives us better trigger support between Jenkinsfile and Github.
https://github.com/jenkinsci/pipeline-github-plugin

**Comment by burukuru** [comment]
!rtg - ai.grakn.graql.internal.query.QueryErrorTest.ai.grakn.graql.internal.query.QueryErrorTest

**Comment by aelred** [comment]
@burukuru does this work?

**Comment by burukuru** [comment]
@aelred Yes it seems to work. Good to merge IMO.

**Pull request merged**
