### PR TITLE
Engine state storage refactor

### PR DESCRIPTION
**Pull request by alexandraorth**
This pull request will allow you to use different StateStorage implementations in the cluster manager. It allows us to have a "distributed" and "in memory" options

+ TaskStateZookeeperStorage implements StateStorage
+ Renaming various StateStorage classes
+ Separated out the Zookeeper connection from the Zookeeper state storage class
+ Serializing the TaskState object to be stored in Zookeeper
+ Refactored engine to have two modes, "in memory" and "distributed"
+ Removed `ClusterManager` and moved it's functionality into `DistributedTaskManager`. 
+ Added class called `SchedulerElector` which controls which machine takes leadership of the cluster
+ Cleaned up non-engine tests to use the in memory engine (GraqlShell, Analytics, Migration)
+ Configured `Scheduler` and `TaskRunner` tests to run in semi-isolation

### CODE REVIEW

**Comment by alexandraorth** [comment]
please retest this please

**Comment by alexandraorth** [comment]
please retest this please

**Comment by alexandraorth** [comment]
i don't think there are enough commits in this pull request so i will add more

**Comment by aelred** [comment]
I don't think there are enough conflicts in this pull request so i will add more

**Comment by fppt** [comment]
@alexandraorth In future these large PRs should ideally be avoided. We should be targeting more incremental PRs. In this PR I see many changes which could have gone into their own PRs.

**Pull request merged**
