### PR TITLE
Adding attributes now behave as adding relationships. I.e. duplicates …

### PR DESCRIPTION
**Pull request by fppt**
…are allowed

Lets see what this breaks :)

### CODE REVIEW

**Comment by aelred** [comment]
I'm not going to merge this until SNB is passing on `master` again - we have to know if it breaks stuff.

**Comment by fppt** [comment]
Agreed. This is VERY high impact.

**Comment by mikonapoli** [comment]
1. What are resources?
2. You really, really hate me :(

**Comment by fppt** [comment]
I have no idea what you talking about.

**Comment by mikonapoli** [comment]
About you hating me, of course.

**Comment by fppt** [comment]
!ci - I swear it used to be green

**Pull request merged**
