### PR TITLE
Allow changing schema concept label using the ID

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
!rtg - some timeout with Janus

**Comment by aelred** [comment]
!rtg - don't know what happened...

**Comment by aelred** [comment]
!rtg - jenkins dead

**Comment by aelred** [comment]
!rtg - another timeout

**Comment by burukuru** [comment]
!rtg

**Comment by aelred** [comment]
!rtg - this looks like it's stuck

**Comment by aelred** [comment]
^ well that was a fun adventure

**Pull request merged**
