### PR TITLE
[stable] Test with Open JDK 8.

### PR DESCRIPTION
**Pull request by burukuru**

### CODE REVIEW

**Comment by fppt** [comment]
!rtg - ai.grakn.client.BatchMutatorClientTest.whenEngineRESTFailsWhileLoadingWithRetryTrue_LoaderRetriesAndWaits

**Comment by burukuru** [comment]
!rtg

**Comment by burukuru** [comment]
!rtg - testing new Jenkins image with OpenJDK

**Comment by burukuru** [comment]
https://github.com/graknlabs/grakn/pull/2255

**Pull request merged**
