### PR TITLE
Prohibit duplicate rules with same patterns

### PR DESCRIPTION
**Pull request by fppt**
Note: This only takes into account patterns with the same variable names.

### CODE REVIEW

**Comment by fppt** [comment]
Passing this over to @kasper-piskorski because after quite a lot of effort I am unable to resolve the reasoner failures.

**Comment by fppt** [comment]
please retest this please

**Comment by fppt** [comment]
please retest this please - Failed due to ai.grakn.test.engine.GraknEngineServerIT.whenSendingTasksToTwoEngines_TheyAllComplete

**Comment by kasper-piskorski** [comment]
please retest this please - Failed due to ai.grakn.test.engine.GraknEngineServerIT.whenSendingTasksToTwoEngines_TheyAllComplete

**Comment by fppt** [comment]
please retest this please - Failed due to ai.grakn.test.graql.analytics.ClusteringTest.testConnectedComponent

**Pull request merged**
