### PR TITLE
Rename `Var` to `VarPattern`

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by aelred** [comment]
please retest this please...

**Comment by aelred** [comment]
please retest this please

**Comment by fppt** [comment]
@aelred rebase/merge required

**Comment by aelred** [comment]
fyi, this one also timed out: http://10.0.1.19:9998/job/unit-test-pull-request-grakn-titan/3476/

**Comment by aelred** [comment]
please retest this please - randomly failing test: http://10.0.1.19:9998/job/unit-test-pull-request-grakn-titan/ai.grakn$grakn-test/3527/testReport/junit/ai.grakn.test.engine.controller/GraqlControllerTest/POSTGraqlInsert_InsertWasExecutedOnGraph/

**Comment by aelred** [comment]
please retest this please - another timeout: http://10.0.1.19:9998/job/unit-test-pull-request-grakn-titan/3533/

**Pull request merged**
