### PR TITLE
Fail packaging when cannot get redis

### PR DESCRIPTION
**Pull request by alexandraorth**

### CODE REVIEW

**Comment by alexandraorth** [comment]
please retest this please

**Comment by burukuru** [comment]
!rtg

**Comment by burukuru** [comment]
!rtg

**Comment by burukuru** [comment]
!rtg - previous test ran on the old image

**Comment by burukuru** [comment]
It's failing because redis dependencies are missing within the containers...
Will need to come up with a different solution.

**Comment by burukuru** [comment]
Think we can close this, https://github.com/graknlabs/grakn/pull/1685 works around the issue by downloading precompiled binaries.

**Pull request closed without merging**
