### PR TITLE
Re-enable `GraqlShellIT`

### PR DESCRIPTION
**Pull request by aelred**
This test was disabled because of random failures, however a recent PR should have fixed it.

### CODE REVIEW

**Comment by fppt** [comment]
Attempt number 329875298346543598236843 is the charm hey @aelred ?

**Comment by aelred** [comment]
This was randomly failing a lot, so I'm going to retest it.

**Comment by aelred** [comment]
please retest this please

**Comment by aelred** [comment]
One last retest: please retest this please

**Comment by aelred** [comment]
@fppt if this passes again, please review and merge!

**Comment by fppt** [comment]
@aelred will do

**Comment by fppt** [comment]
@aelred I am going to retest this one in the morning. If it passes. I will merge :)

**Comment by fppt** [comment]
please retest this please

**Comment by fppt** [comment]
please retest this please

**Comment by fppt** [comment]
please retest this please

**Pull request merged**
