### PR TITLE
[Stable] Refine resolution plan based on rule resolvability

### PR DESCRIPTION
**Pull request by kasper-piskorski**

### CODE REVIEW

**Comment by fppt** [comment]
!rtg - CI is working again

**Comment by fppt** [comment]
@kasper-piskorski this PR appears to actually be failing on CI. Could you merge with central/stable and push back up? 

I would like to check if that will help.

**Comment by fppt** [comment]
@kasper-piskorski I think this PR has broken CI. The validation queries are taking forever to run. They usually take 20 mins but now it's been over 1 hour.

**Comment by kasper-piskorski** [comment]
ok, this is not safe, saving for later

**Pull request closed without merging**
