### PR TITLE
Fix docs saying inference is disabled-by-default

### PR DESCRIPTION
**Pull request by aelred**

### CODE REVIEW

**Comment by fppt** [comment]
This should be on stable

**Comment by aelred** [comment]
@fppt good point!

**Comment by aelred** [comment]
!rtg - jenkins got upset by switching to `stable`

**Comment by aelred** [comment]
jenkins is still upset, will close and re-open :/

**Comment by fppt** [comment]
@aelred Jenkins still hates you

**Comment by aelred** [comment]
!rtg - so weird... let's try again

**Comment by aelred** [comment]
!rtg whaaaaaaat

**Comment by aelred** [comment]
ok I'm closing this and opening a whole new PR

**Pull request closed without merging**
