### PR TITLE
Change exception handling in `PathQueryImpl`

### PR DESCRIPTION
**Pull request by alexandraorth**

### CODE REVIEW

**Comment by fppt** [comment]
please retest this please

**Comment by fppt** [comment]
please retest this please - ai.grakn.test.graql.analytics.ClusteringTest.testConnectedComponent

**Comment by fppt** [comment]
please retest this please - ai.grakn.test.engine.GraknEngineServerIT.whenEngine1StopsATaskBeforeExecution_TheTaskIsStopped

**Comment by fppt** [comment]
please retest this please

**Comment by bolerio** [comment]
pending for many days so I'm closing this....

**Pull request closed without merging**
